name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt update
        sudo apt install mingw-w64
        rustup target add x86_64-pc-windows-gnu
        cargo build -r --target x86_64-pc-windows-gnu
      
